name: test-new-binaries
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI
        description: 'version to build'
        # Default value if no value is explicitly provided
        default: '0.0.1'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  # skip tests
  dist:
    # needs: tests
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      -
        name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-dist-${{ hashFiles('**/Cargo.lock') }}
      -
        name: Build distributables
        run: nix-shell --command "make dist"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
        with:
          tag_name: ${{ github.event.inputs.name }}
          release_name: Release ${{ github.event.inputs.name }}
          draft: false
          prerelease: false
                    
      - name: Find Dist directory
        run: |
          dist_dir=$(find / -type d -name "chirpstack-concentratord-sx1302_4.2.0-test.2_arm64.tar.gz" 2>/dev/null | head -n 1)
          if [ -n "$dist_dir" ]; then
            echo "Dist directory found at $dist_dir"
          else
            echo "Dist directory not found"
          fi

      - name: Upload files to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist
          asset_name: binaries-${{ github.event.inputs.name }}.zip
          asset_content_type: application/zip

